### ISSUE TITLE
Question -- Future dotstar compatibility? Also how to look at other MCU pins

### ISSUE THREAD

**Issue by Kcdc3d** [julianschill/moonshine#3]
Hi there, currently using your led-effects plugin with great success for two sets of dotstar runs. I asked this  over at led-control with no answer, but wanted to see if you had any insight by chance. Is there going to be dotstar support in the future? Also, I have my LEDs connected to a Pico that's plugged into my main 4b via USB. Right now it's all dotstars but will be adding some neopixel leds, so I am wondering if there's a method to get led-control to look at the Pico's pins and/or the controller board's neopixel header. Thanks!

**Comment by julianschill** [comment]
I have no insights to LEDcontrol, but I doubt there will be dotstar support. Also it won't use the Picos pins as it is designes to use the raspberries one.
