### ISSUE TITLE
Issues defining RGB Order

### ISSUE THREAD

**Issue by meffken** [julianschill/moonshine#4]
Maybe its my fault, but I'm failing at assigning the right Pixel Order. I tried to define it via ssh with "sudo ledcontrol --led_count 150 --led_pixel_order GRB" but it still keeps in RGBW Mode. Also tried editing the ledcontrol.default file.

**Comment by julianschill** [comment]
Edit /etc/default/ledcontrol with `sudo nano /etc/default/ledcontrol` and then restart it with `sudo service ledcontrol restart`

**Comment by meffken** [comment]
Worked for me. Thank you for your help and this nice Addon! Love it!
