### ISSUE TITLE
Can't edit etc/default/ledcontrol

### ISSUE THREAD

**Issue by ChrK2017** [julianschill/moonshine#7]
I can not edit the file etc/default/ledcontrol...
When I open the file though Putty or WinSCP, it is in a read-only state and I can not change the permissions of the file.

This means that when I want to edit the file I get a Access Denied error in Putty...
I therefore cannot change my setup...

**Comment by julianschill** [comment]
You need root access to edit the file. In putty you can use `sudo nano /etc/default/ledcontrol` to edit the file.

**Comment by ChrK2017** [comment]
Nice that worked... The file have been changed now :) Thanks!
