### ISSUE TITLE
Support for mcu connected neopixel?

### ISSUE THREAD

**Issue by germzx** [julianschill/moonshine#8]
Using this for my 3d printer, with neopixel connected to an SKR e3 v3 and SKR pico and my rasp pi as the host. Is there a way to designate those pin connections to utilize this script or must it be connected to the pi?

If not, is it fine to have this git floating in my filespace or should I figure out how to uninstall? There is no uninstall script in the repo and honestly I'm not confident with navigating pi beyond written instructions and the local config files for my printer. 

Thanks

**Comment by julianschill** [comment]
For this solution it must be connected to the pi as it relies on a different piece of software, that runs on the pi and knows nothing about the MCUs. Please consider using [this](https://github.com/julianschill/klipper-led_effect) if you want connect the LEDs to the MCU and control them from Klipper. You can leave the git in your filespace it is causing no harm. Just remove it from your moonraker config.
